### ISSUE TITLE
 Installation

### ISSUE THREAD

**Issue by yousseffjel** [akibahmed229/nixos#17]
hey bro first think u do great work for this config, just want to tell u if u can tell me more about the installation steps if u can. 
U do great work thank u.

**Comment by akibahmed229** [comment]
**Before installing NixOS on your desktop, it's recommended to try it out in a virtual machine.**

**Installation steps:**

*  Follow the installation guide on GitHub: [https://github.com/akibahmed229/nixos?tab=readme-ov-file#installation-steps](https://github.com/akibahmed229/nixos?tab=readme-ov-file#installation-steps)
*  During installation, you'll be prompted for:
    * Username: Choose any username you like.
    * Hostname: Enter "virt" for a virtual machine. ( available hostname:- virt, desktop)
    * Device name: This will likely be something like "/dev/vda" for a VM.

**After installation:**

*  Open a terminal with "Super + Return".
*  Open dmenu with "Super + Space".
*  Navigate to the `~/.config/flake` directory in the terminal.
*  Fix permission issues by running these commands:

```
chown -R yourUserName:users *
chown -R yourUserName:users .*
```


note: the host virt have dwm as tilling wm
